services:
  db-postgres: # 5432 default
    image: postgres:16
    environment:
      - POSTGRES_DB=LocalLink_db
      - POSTGRES_USER=LocalLink_user
      - POSTGRES_PASSWORD=password123
    # volumes:
    #   - ./postgres_db_data:/var/lib/postgresql/data/
    ports:
      - "5000:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U LocalLink_user -d LocalLink_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres_db_data:/var/lib/postgresql/data/

volumes:
  postgres_db_data: